### ISSUE TITLE
The issue of UnicodeDecodeError on using python 3.8.3.

### ISSUE THREAD

**Issue by tkb-tech** [dgerosa/gwdet#3]
Hey! I'm Japanese user of gwdet, and I'm not good at English, so Im so sorry if I'm saying too directly or impolitely.
I have some issue about unicode decode error like this.

Traceback (most recent call last):
  File "/Users/tkb/opt/anaconda3/lib/python3.8/site-packages/gwdet/gwdet.py", line 545, in __call__
    return self.eval(m1,m2,z)
  File "/Users/tkb/opt/anaconda3/lib/python3.8/site-packages/gwdet/gwdet.py", line 536, in eval
    interpolant = self.interpolate()
  File "/Users/tkb/opt/anaconda3/lib/python3.8/site-packages/gwdet/gwdet.py", line 522, in interpolate
    with open(self.binfile, 'rb') as f: interpolant = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x83 in position 0: ordinal not in range(128)

I don't have any issue on python 2.7, but I have this issue on python3.8.
(I faced this issue in OS X 10.15.5 and also 10.13.6.)
Now I'm wondering this module is compatible with py 3.7.
Could you give me any advise or something. 

I'm truely sorry for troubling you.

Best,

**Comment by dgerosa** [comment]
Hi there,

thanks for your note. This issue seems to be OS-dependent. The safest option would be to regenerate the checkpoint files on your machine and use those. If this is too computationally expensive, you can try replacing
`pickle.load(...)`
with 
`pickle.load(..., encoding="bytes")`.

Davide

**Comment by tkb-tech** [comment]
Thank you so much for your comment.
I see, now I am trying to regenerate the check points by myself (I used checkpoint files which you kindly made.)
Thank you again!

Takebe
